<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX51sxl5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX51sxl5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX51sxl5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX51sxl5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX51sxl5\appProdProjectContainer(array(
    'container.build_hash' => 'X51sxl5',
    'container.build_id' => '8f8d634b',
    'container.build_time' => 1519747542,
));
