<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQaufmuv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQaufmuv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQaufmuv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQaufmuv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQaufmuv\appProdProjectContainer(array(
    'container.build_hash' => 'Qaufmuv',
    'container.build_id' => '05e61184',
    'container.build_time' => 1519314970,
));
