tasca_index:
    path:     /
    defaults: { _controller: "GestorProjectesBackendBundle:Tasca:index" }
    methods:  GET

tasca_show:
    path:     /{id}/show
    defaults: { _controller: "GestorProjectesBackendBundle:Tasca:show" }
    methods:  GET

tasca_new:
    path:     /new
    defaults: { _controller: "GestorProjectesBackendBundle:Tasca:new" }
    methods:  [GET, POST]

tasca_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestorProjectesBackendBundle:Tasca:edit" }
    methods:  [GET, POST]

tasca_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestorProjectesBackendBundle:Tasca:delete" }
    methods:  DELETE
