usuaris_index:
    path:     /
    defaults: { _controller: "GestorProjectesBackendBundle:Usuaris:index" }
    methods:  GET

usuaris_show:
    path:     /{id}/show
    defaults: { _controller: "GestorProjectesBackendBundle:Usuaris:show" }
    methods:  GET

usuaris_new:
    path:     /new
    defaults: { _controller: "GestorProjectesBackendBundle:Usuaris:new" }
    methods:  [GET, POST]

usuaris_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestorProjectesBackendBundle:Usuaris:edit" }
    methods:  [GET, POST]

usuaris_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestorProjectesBackendBundle:Usuaris:delete" }
    methods:  DELETE
