<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAm551k7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAm551k7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAm551k7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAm551k7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAm551k7\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Am551k7',
    'container.build_id' => 'c6ef84bb',
    'container.build_time' => 1519661624,
));
