<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGhznwq5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGhznwq5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGhznwq5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGhznwq5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGhznwq5\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ghznwq5',
    'container.build_id' => 'b280527c',
    'container.build_time' => 1521557536,
));
